# Generated by Django 3.0.7 on 2020-06-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField(default=0)),
                ('titre', models.CharField(default='Prestation X', max_length=50)),
            ],
            options={
                'verbose_name': 'prestation basique',
                'ordering': ['titre'],
            },
        ),
    ]
