# Generated by Django 3.0.7 on 2020-06-16 14:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('nom', models.CharField(max_length=50, null=True)),
                ('societe', models.CharField(max_length=100, null=True)),
                ('adresse', models.TextField(max_length=200)),
                ('complement_adresse', models.TextField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'client',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='prestation',
            options={'ordering': ['titre'], 'verbose_name': 'prestation'},
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(default=django.utils.timezone.now, verbose_name='Date création du devis')),
                ('date_planification', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Planification prévue pour le devis')),
                ('reduction', models.IntegerField(default=0, max_length=2)),
                ('oral', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devis.Client')),
            ],
            options={
                'verbose_name': 'devis',
                'ordering': ['date_creation'],
            },
        ),
    ]
