# Generated by Django 3.0.7 on 2020-06-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_auto_20200616_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='prestations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devis.Prestation'),
        ),
    ]
