# Generated by Django 3.0.7 on 2020-07-18 12:03

from django.db import migrations, models
import django.db.models.deletion
import prestations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='Autres', max_length=50)),
                ('icone', models.CharField(blank=True, default='miscellaneous_services', max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'db_table': 'prestations_categorie',
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Marque',
                'db_table': 'prestations_marque',
            },
        ),
        migrations.CreateModel(
            name='PieceDetacheeStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='Pièce détachée standard', max_length=50)),
            ],
            options={
                'verbose_name': 'Pièce détachée sans prix',
                'db_table': 'prestations_piecedetacheestandard',
            },
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='Prestation standard', max_length=50)),
                ('categorie', models.ForeignKey(default=prestations.models.get_autre_categorie, on_delete=django.db.models.deletion.SET_DEFAULT, to='prestations.Categorie')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_prestations.prestation_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Prestation standard, sans coût',
                'db_table': 'prestations_prestation',
            },
        ),
        migrations.CreateModel(
            name='PieceDetacheeAvecPrix',
            fields=[
                ('piecedetacheestandard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestations.PieceDetacheeStandard')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Pièce détachée avec prix associé',
                'db_table': 'prestations_piecedetacheeavecprix',
            },
            bases=('prestations.piecedetacheestandard',),
        ),
        migrations.CreateModel(
            name='PrestationCoutFixe',
            fields=[
                ('prestation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestations.Prestation')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Prestation à coût fixe',
                'db_table': 'prestations_pestationcoutfixe',
            },
            bases=('prestations.prestation',),
        ),
        migrations.CreateModel(
            name='PrestationMainOeuvre',
            fields=[
                ('prestation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestations.Prestation')),
                ('tauxHoraire', models.DecimalField(decimal_places=2, default=55, max_digits=7)),
            ],
            options={
                'verbose_name': "Prestation representant 1 heure de main d'oeuvre",
                'db_table': 'prestations_prestationmainoeuvre',
            },
            bases=('prestations.prestation',),
        ),
        migrations.CreateModel(
            name='PrestationNouvelle',
            fields=[
                ('prestation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestations.Prestation')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Prestation répondant à un besoin ponctuel',
                'db_table': 'prestations_prestationnouvelle',
            },
            bases=('prestations.prestation',),
        ),
        migrations.CreateModel(
            name='PrestationPneumatique',
            fields=[
                ('prestation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestations.Prestation')),
                ('prixAchat', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('dimensions', models.PositiveIntegerField()),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestations.Marque')),
            ],
            options={
                'verbose_name': 'Prestation concernant les pneus',
                'db_table': 'prestations_prestationpneumatique',
            },
            bases=('prestations.prestation',),
        ),
        migrations.CreateModel(
            name='PrestationCoutVariableStandard',
            fields=[
                ('prestation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestations.Prestation')),
                ('pieces_detachees', models.ManyToManyField(to='prestations.PieceDetacheeStandard')),
            ],
            options={
                'verbose_name': 'Prestation à prix variable, sans prix associés',
                'db_table': 'prestations_prestationcoutvariablestandard',
            },
            bases=('prestations.prestation',),
        ),
        migrations.CreateModel(
            name='PrestationCoutVariableConcrete',
            fields=[
                ('prestation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prestations.Prestation')),
                ('pieces_detachees', models.ManyToManyField(to='prestations.PieceDetacheeAvecPrix')),
            ],
            options={
                'verbose_name': 'Prestation à prix variable, prix des pièces connus',
                'db_table': 'prestations_prestationcoutvariableconcrete',
            },
            bases=('prestations.prestation',),
        ),
    ]
