# Generated by Django 3.0.7 on 2020-07-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prestationcoutfixe',
            table='prestations_prestationcoutfixe',
        ),
    ]
