# Generated by Django 3.0.7 on 2020-07-18 21:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0002_auto_20200718_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestationcoutfixe',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
